const Language = [
    { code: 'en', label: 'English' },
    { code: 'de', label: 'German' },
    { code: 'ar', label: 'Arabic' },
    { code: 'es', label: 'Spanish' },
    { code: 'fr', label: 'French' },
    { code: 'he', label: 'Hebrew' },
    { code: 'it', label: 'Italian' },
    { code: 'nl', label: 'Dutch' },
    { code: 'no', label: 'Norwegian' },
    { code: 'pt', label: 'Portuguese' },
    { code: 'ru', label: 'Russian' },
    { code: 'sv', label: 'Swedish' },
    { code: 'zh', label: 'Chinese' },
];

const Country = [
    { code: 'ae', label:'United Arab Emirates' },
    { code: 'ar', label:'Argentina' },
    { code: 'at', label:'Austria' },
    { code: 'au', label:'Australia' },
    { code: 'be', label:'Belgium' },
    { code: 'bg', label:'Bulgaria' },
    { code: 'br', label:'Brazil' },
    { code: 'ca', label:'Canada' },
    { code: 'ch', label:'Switzerland' },
    { code: 'cn', label:'China' },
    { code: 'co', label:'Colombia' },
    { code: 'cu', label:'Cuba' },
    { code: 'cz', label:'Czech Republic' },
    { code: 'de', label:'Germany' },
    { code: 'eg', label:'Egypt' },
    { code: 'fr', label:'France' },
    { code: 'gb', label:'United Kingdom' },
    { code: 'gr', label:'Greece' },
    { code: 'hk', label:'Hong Kong' },
    { code: 'hu', label:'Hungary' },
    { code: 'id', label:'Indonesia' },
    { code: 'ie', label:'Ireland' },
    { code: 'il', label:'Israel' },
    { code: 'in', label:'India' },
    { code: 'it', label:'Italy' },
    { code: 'jp', label:'Japan' },
    { code: 'kr', label:'South Korea' },
    { code: 'lt', label:'Lithuania' },
    { code: 'lv', label:'Latvia' },
    { code: 'ma', label:'Morocco' },
    { code: 'mx', label:'Mexico' },
    { code: 'my', label:'Malaysia' },
    { code: 'ng', label:'Nigeria' },
    { code: 'nl', label:'Netherlands' },
    { code: 'no', label:'Norway' },
    { code: 'nz', label:'New Zealand' },
    { code: 'ph', label:'Philippines' },
    { code: 'pl', label:'Poland' },
    { code: 'pt', label:'Portugal' },
    { code: 'ro', label:'Romania' },
    { code: 'rs', label:'Serbia' },
    { code: 'ru', label:'Russia' },
    { code: 'sa', label:'Saudi Arabia' },
    { code: 'se', label:'Sweden' },
    { code: 'sg', label:'Singapore' },
    { code: 'si', label:'Slovenia' },
    { code: 'sk', label:'Slovakia' },
    { code: 'th', label:'Thailand' },
    { code: 'tr', label:'Turkey' },
    { code: 'tw', label:'Taiwan' },
    { code: 'ua', label:'Ukraine' },
    { code: 'us', label:'United States' },
    { code: 've', label:'Venezuela' },
    { code: 'za', label:'South Africa' },
];

const Categories = [
  { code: 'business', label: 'Business' },
  { code: 'entertainment', label: 'Entertainment' },
  { code: 'general', label: 'General' },
  { code: 'health', label: 'Health' },
  { code: 'science', label: 'Science' },
  { code: 'sports', label: 'Sports' },
  { code: 'technology', label: 'Technology' },
  { code: 'all', label: 'All Categories' } // Default category
];

const NewsType = [
  {code: 'heading', label: 'Heading Only'},
  {code: 'In depth', label: 'In depth articles'},
  {code: 'both', label: 'Both'},
]

const Notifications = [
  {code: 'daily', label: 'Daily Updates'},
  {code: 'breakingNewsOnly', label: 'Breaking News Only'},
  {code: 'notifications', label: 'No Notifications'},
]

    
export default {Country, Language, Categories, NewsType, Notifications};